### ISSUE TITLE
Wrong type in Windows 7

### ISSUE THREAD

**Issue by exphck1337** [notscimmy/pplib#2]
Hello, there is a small error in [this line](https://github.com/notscimmy/pplib/blob/0da2fac8a24efb60db42c2d79d6b6f3c8ccc5646/pplib/pplib.cpp#L32) that makes pplib not work in Windows 7, in Windows 7 EPROCESS::Flags2(offset 0x43C, EPROCESS::Protection in Windows 8/8.1/10) is ULONG(4 bytes) not uint8_t(1 byte), so you are just writing a 1 byte when you need write 4 bytes to enable ppl in windows 7.

https://github.com/notscimmy/pplib/blob/0da2fac8a24efb60db42c2d79d6b6f3c8ccc5646/pplib/pplib.cpp#L32

Should be:
```
if (version == WINDOWS7)
	*(DWORD*)pPPL |= 1 << 0xB;
```

**Comment by notscimmy** [comment]
Unfortunately, I haven't had much of a chance to test this on Windows 7...hence the bug. 

Please submit a pull request and I will merge it in. Thanks a bunch!
